### ISSUE TITLE
sentiment num 

### ISSUE THREAD

**Issue by liruijia** [victor7246/jointtsmodel#1]
When the number of sentiment equals 4, the code reports an error

error is "ValueError: operands could not be broadcast together with shapes (5,) (5,4) "

how to change this code ，please

**Comment by victor7246** [comment]
Thanks for pointing this out. For JST and TSWE, we had an axis mismatch. The bug has been fixed in the latest push. Confirm to me if you still find the issue. Else I will close the issue.
