### ISSUE TITLE
How to calculate accuracy for each method?

### ISSUE THREAD

**Issue by seilsepour** [victor7246/jointtsmodel#2]
Hello victor7246,
Please just tell me how to get accuracy for each model. Something like this:

`testLoss, testAcc = model.evaluate(x_test_pad, y_test)

print('Test loss:', testLoss)

print('Test accuracy:', testAcc)`

**Comment by victor7246** [comment]
Extract the model.pi() matrix after fitting a topic-sentiment model and use argmax on axis 1 or 2 (depending upon the model) to get the sentiment label for each document and each topic. Then use standard accuracy/f1 scores to evaluate against the ground truth.
