### ISSUE TITLE
How to set different values of γ

### ISSUE THREAD

**Issue by cartantino** [victor7246/jointtsmodel#3]
Hi,
First thing first: thanks for sharing your work!
I'd like to know if there is a chance for setting different values of γ for positive document-sentiment
associations and negative document-sentiment associations.
For example, equals to 0.01 for positive document-sentiment associations and to 5.0 for negative document-sentiment associations.

Kind regards,
Costantino.

**Comment by victor7246** [comment]
HI,
All the models implemented as part of this library uses symmetric document-sentiment priors. Your suggestion opens up the possibility of a new JST model. Feel free to submit a pull request.

Thanks and regards,
